[project]
name = "gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "torch>=2.6.0",
]

[dependency-groups]
dev = [
    "uv>=0.5.30",
]
